version: "3.1"

services:
    db:
        container_name: mongoDB
        image: mongo:latest
        restart: always
        volumes:
            - ./testdb:/data/db
        environment:
            - MONGO_INITDB_DATABASE= 9gag-clone
        ports:
            - 27000:27000